'''
This file contains definition of the data files used. These constants should be used instead of hard coding paths
elsewhere as this will allow the locations to be changed of modified.
'''
import os
import json

''' Data used to drive the application, can be deleted, but will need to be re-generated '''
datadir = "../../data"
''' SRC data containing read only source information '''
srcdatadir = "../../source-data"
''' Generated temp data '''
gentmpdir = "../../generate-tmp"

''' The ID map mapping tripos/course/subject to a unique ID,(generated and updated). '''
idmapFilePath = datadir+"/idmap.csv"
''' Definition of the tripos courses subjects (required source material) '''
topFilePath = srcdatadir+"/top.csv"
''' Input definition of static course ursl (optional source material) '''
pdfsFilePath = srcdatadir+"/pdfs.csv"
''' Update set of static course urls (generated and updated) '''
pdfsDataFilePath = datadir+"/pdfs.csv"
''' Output of tripos, course, subject (generated and updated by topgen.py) '''
topJsonFilePath = datadir+"/top.json"
''' generated set of subjects (generated by topgen.py) '''
subjectsJsonFilePath = gentmpdir+"/subjects.json"
''' list of data from PDNfeed and PDN gen '''
pdnSrcFilePath = srcdatadir+'/pdn-src.csv'
''' location of new source spreadsheets '''
newCourseSheetDir = srcdatadir+'/new-course-sheets'

''' prefix used for all details files '''
detailsPrefix = "details_"
# create missing directories if missing
if not os.path.isdir(datadir):
    os.mkdir(datadir)

if not os.path.isdir(gentmpdir):
    os.mkdir(gentmpdir)


def getDetailFile(id):
    return "%s/%s%s.json" % (datadir, detailsPrefix, id)

def saveDetailFile(data, id):
    c = open(getDetailFile(id),'wb')
    json.dump(data,c)
    c.close()
